# Generated by Django 2.0 on 2018-09-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=35, null=True)),
                ('website', models.URLField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('company_type', models.CharField(choices=[('FOOD & DRINKS', 'Food & Drinks'), ('ENTERTAINMENT', 'Entertainment'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('RELIGIOUS SERVICES', 'Religious Services'), ('OTHER', 'Other')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('FOOD & DRINKS', 'Food & Drinks'), ('ENTERTAINMENT', 'Entertainment'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('RELIGIOUS SERVICES', 'Religious Services'), ('OTHER', 'Other')], max_length=25)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('average_rating', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='company.CompanyName')),
            ],
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='companyname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='company.CompanyName'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='companyname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='company.CompanyName'),
        ),
    ]
