# Generated by Django 2.0 on 2018-09-24 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=35, null=True)),
                ('company_image', models.URLField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, max_length=50, null=True)),
                ('twitter', models.URLField(blank=True, max_length=50, null=True)),
                ('pintrest', models.URLField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.TimeField(blank=True, null=True)),
                ('friday_open', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.TimeField(blank=True, null=True)),
                ('sunday_open', models.TimeField(blank=True, null=True)),
                ('weekdays_open', models.TimeField(blank=True, null=True)),
                ('weekend_open', models.TimeField(blank=True, null=True)),
                ('weekend_close', models.TimeField(blank=True, null=True)),
                ('weekdays_close', models.TimeField(blank=True, null=True)),
                ('monday_close', models.TimeField(blank=True, null=True)),
                ('tuesday_close', models.TimeField(blank=True, null=True)),
                ('wednesday_close', models.TimeField(blank=True, null=True)),
                ('thursay_close', models.TimeField(blank=True, null=True)),
                ('friday_close', models.TimeField(blank=True, null=True)),
                ('saturday_close', models.TimeField(blank=True, null=True)),
                ('sunday_close', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('company_type', models.CharField(choices=[('FOOD & DRINKS', 'Food & Drinks'), ('ENTERTAINMENT', 'Entertainment'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('RELIGIOUS SERVICES', 'Religious Services'), ('NIGHTLIFE', 'Nightlife')], max_length=25)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('company_image', models.URLField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('FOOD & DRINKS', 'Food & Drinks'), ('ENTERTAINMENT', 'Entertainment'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('RELIGIOUS SERVICES', 'Religious Services'), ('OTHER', 'Other')], max_length=25)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='company.CompanyName')),
            ],
        ),
        migrations.AddField(
            model_name='companyhours',
            name='companyname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='company.CompanyName'),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='companyname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='company.CompanyName'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='companyname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='company.CompanyName'),
        ),
    ]
