# Generated by Django 2.0 on 2018-09-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
    ]
