# Generated by Django 2.0 on 2018-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_review_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
