# Generated by Django 2.0 on 2018-09-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyname_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_type',
            field=models.CharField(choices=[('FOOD & DRINKS', 'Food & Drinks'), ('ENTERTAINMENT', 'Entertainment'), ('SERVICES', 'Services'), ('PRODUCTS', 'Products'), ('RELIGIOUS SERVICES', 'Religious Services'), ('NIGHTLIFE', 'Nightlife')], max_length=25),
        ),
    ]
