# Generated by Django 2.0 on 2018-09-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180918_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactinfo',
            name='facebook',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='instagram',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='pintrest',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='twitter',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
