# Generated by Django 2.0 on 2018-09-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20180918_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.TimeField(blank=True, null=True)),
                ('friday_open', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.TimeField(blank=True, null=True)),
                ('sunday_open', models.TimeField(blank=True, null=True)),
                ('weekdays_open', models.TimeField(blank=True, null=True)),
                ('weekend_open', models.TimeField(blank=True, null=True)),
                ('weekend_close', models.TimeField(blank=True, null=True)),
                ('weekdays_close', models.TimeField(blank=True, null=True)),
                ('monday_close', models.TimeField(blank=True, null=True)),
                ('tuesday_close', models.TimeField(blank=True, null=True)),
                ('wednesday_close', models.TimeField(blank=True, null=True)),
                ('thursay_close', models.TimeField(blank=True, null=True)),
                ('friday_close', models.TimeField(blank=True, null=True)),
                ('companyname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='company.CompanyName')),
            ],
        ),
    ]
