# Generated by Django 2.0 on 2018-09-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhours',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyhours',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
