# Generated by Django 2.0 on 2018-09-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20180918_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='company_image',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
