# Generated by Django 2.0 on 2018-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companyname_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactinfo',
            name='company_image',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companycontactinfo',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companycontactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
