# Generated by Django 2.0 on 2018-09-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companyname_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactinfo',
            name='company_image',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
